### PR TITLE
Create test.Rmd

### PR DESCRIPTION
**Pull request by Ken-Vu**
Test file

### CODE REVIEW

**Comment by jonthegeek** [comment]
This is the template I copy to create new book repositories. Is that what you were trying to figure out?

**Comment by Ken-Vu** [comment]
To clarify, me and Lydia were planning to use it as a tutorial on how to
accept or reject pull requests as part of book club facilitating training
(hence, the bogus pull request with a text file).  The actual r4ds book
club repo's pull requests had the names of other people on it.  Thus, I
thought to use this repo to demonstrate how to handle pull requests for
bookdowns without actually going through the motions to change the repo
actually and exposing other people's names and faces.

**Comment by jonthegeek** [comment]
Aha, that somewhat makes sense. We can make a fake repo purely for this purpose that won't impact anything, if you haven't already done what you need. I'd rather do that than have a fake PR hanging open in a used repo.

**Comment by lgibson7** [comment]
Hi @jonthegeek. Sorry for the confusion. I asked Ken to make this PR and then I didn't get around to making the necessarily screenshots I wanted to. I'll work with Ken to do a fake repo for future PRs. Thank you!

**Pull request closed without merging**
